-- Create a table for users (extending Supabase Auth if needed, or standalone)
create table if not exists public.users (
  id uuid references auth.users not null primary key,
  email text,
  role text default 'user' check (role in ('user', 'admin')),
  trust_rank int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Establish Row Level Security (RLS)
alter table public.users enable row level security;

-- Policies for users
do $$ begin
  create policy "Public profiles are viewable by everyone." on public.users for select using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert their own profile." on public.users for insert with check (auth.uid() = id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can update own profile." on public.users for update using (auth.uid() = id);
exception when duplicate_object then null; end $$;

-- Trigger to handle new user signup automatically
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.users (id, email, role, trust_rank)
  values (new.id, new.email, 'admin', 0)  -- DEFAULT TO ADMIN FOR PROTOTYPE
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to ensure we attach the new function
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- Source Metadata Table
create table if not exists public.source_metadata (
  domain text primary key,
  owner_name text,
  funding_type text, 
  bias_rating text, 
  country_of_origin text,
  establishment_year int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.source_metadata enable row level security;

-- Policies for source_metadata
-- EMERGENCY FIX: Allow all authenticated users to manage metadata for the prototype
drop policy if exists "Subject metadata is public" on public.source_metadata;
drop policy if exists "Admins can manage source metadata" on public.source_metadata;

create policy "Authenticated users can manage metadata" on public.source_metadata
  for all using (auth.role() = 'authenticated');

create policy "Public read access" on public.source_metadata
  for select using (true);


-- Submissions Table
create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users not null,
  url text not null,
  original_headline text,
  credibility_score int, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.submissions enable row level security;

-- Policies for submissions
drop policy if exists "Users can view own submissions" on public.submissions;
drop policy if exists "Users can create submissions" on public.submissions;
drop policy if exists "Admins can view all submissions" on public.submissions;

-- Allow all authenticated users to do everything for submissions
create policy "Authenticated users can manage submissions" on public.submissions
  for all using (auth.role() = 'authenticated');

-- *** CRITICAL FIX: Make sure the current user is an admin (just in case) ***
update public.users set role = 'admin';

-- Content Flags Table (Community Moderation)
create table if not exists public.content_flags (
  id bigint generated by default as identity primary key,
  url text not null,
  reason text,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.content_flags enable row level security;

-- Policies for content_flags
create policy "Anyone can insert flags" on public.content_flags
  for insert with check (true);

create policy "Admins can view all flags" on public.content_flags
  for select using (auth.role() = 'authenticated');
