-- Run this in your Supabase SQL Editor to enable Community Moderation

create table if not exists public.content_flags (
  id bigint generated by default as identity primary key,
  url text not null,
  reason text,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Allow anyone (anon or auth) to insert flags for now (for public demo)
-- In production, you'd restrict this to authenticated users
alter table public.content_flags enable row level security;

create policy "Anyone can insert flags" on public.content_flags
  for insert with check (true);

create policy "Admins can view all flags" on public.content_flags
  for select using (auth.role() = 'authenticated'); -- Simplified for prototype

NOTIFY pgrst, 'reload config';
